server:
  port: 8088
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: admin
  jpa:
#    hibernate:
#      ddl-auto: update
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog.xml