server:
  port: 8088
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: admin
    password: admin
  jpa:
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog.xml
  profiles:
    active: 
      - production