name: build sdc-daily-status
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true
        cache: maven
   
    - name: Build with Maven
      run: mvn -B clean package --file ./sdc-daily-status/pom.xml
