name: build sdc-daily-status
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        check-latest: true
        cache: maven
   
    - name: Build with Maven
      run: mvn -B clean package --file ./sdc-daily-status/pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_POC_USERNAME }}
        password: ${{ secrets.DOCKER_POC_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./sdc-daily-status/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/sdc-daily-status:latest
